---
title: "Plant Protein Combined Surveys"
format: dashboard
scrolling: true
include-in-header:
  text: |
    <link rel="shortcut icon" href="/assets/images/logos/b2flogo.png" />
    <link rel="icon" type="image/x-icon" href="/assets/images/logos/favicon.ico">
    <link rel="stylesheet" type="text/css" href="styles.css">
    <script src="scripts.js"></script>
---

```{r}
source("pp_combined.R")
source("bcs.R")
```

# Summary

## Row {height="220px"}

### Column

::: {.valuebox icon="bar-chart-steps" color="secondary" title="Industry Confidence"}

`r curr_ic`

`r curr_ic_deltas_html`

<i class="bi bi-info-circle info-icon" data-bs-toggle="popover" data-bs-placement="top" data-bs-content="`r curr_ic_tooltip`"></i>

:::


### Column

::: {.valuebox icon="cloud-sun" color="secondary" title="Business Uncertainty"}

`r curr_bu`

`r curr_bu_deltas_html`

<i class="bi bi-info-circle info-icon" data-bs-toggle="popover" data-bs-placement="top" data-bs-content="`r curr_bu_tooltip`"></i>
  
:::


### Column

::: {.valuebox icon="people" color="light" title="Employment Outlook"}

`r curr_eo`

`r curr_eo_deltas_html`

<i class="bi bi-info-circle info-icon" data-bs-toggle="popover" data-bs-placement="top" data-bs-content="`r curr_eo_tooltip`"></i>

:::


## Row

### Column
```{r}
#| title: "Business Uncertainty"
uncertainty_bar
```

### Column
```{r}
#| title: "3-Year Business Plans"
plans_pie
```
## Row

### Column
```{r}
#| title: "Competitive Position"
comp_past_3_pie
```

### Column
```{r}
#| title: "Regional Sales Distribution"
regions_dist_donut
```

## Row

### Column

```{r}
#| title: "Industry Confidence"
# bcs_cof
```


# Production & Orders

## Row

```{r}
#| title: "Recent Orders"
orders_past_3_pie
```

```{r}
#| title: "Current Order Books"
orders_curr_pie
```

## Row

```{r}
#| title: "Production Level"
prod_lvl_box
```

```{r}
#| title: "Production Capacity"
prod_cap_bar
```

## Row

```{r}
#| title: "Current Stocks of Finished Products"
stocks_curr_pie
```

## Row

```{r}
#| title: "Production - Past 3 Months"
prod_past_3_pie
```

```{r}
#| title: "Euro Area Historical"
# bcs_m_ea_prod_trend
```

```{r}
#| title: "Production Expectations - Next 3 Months"
prod_next_3_pie
```


## Row

```{r}
#| title: "Factors Limiting Production"
prod_limits_bar
```

# Inputs & Prices

## Row

```{r}
#| title: "Input Costs (Excluding Labour) - Past 3 Months"
costs_past_3_pie
```

```{r}
#| title: "Expected Input Costs (Excluding Labour) - Next 3 Months"
costs_next_3_pie
```

## Row

```{r}
#| title: "Selling Prices - Past 3 Months"
prices_past_3_pie
```

```{r}
#| title: "Expected Selling Prices - Next 3 Months"
prices_next_3_pie
```   

# Labour

## Row

```{r}
#| title: "Staff Numbers - Past 3 Months"
emp_past_3_pie
```

```{r}
#| title: "Expected Staff Numbers - Next 3 Months"
emp_next_3_pie
``` 

## Row

```{r}
#| title: "Labour Costs - Past 3 Months"
lab_costs_past_3_pie
```
```{r}
#| title: "Labour Costs"
lab_costs_lvl_pie
```

## Row

```{r}
#| title: "Finding Skilled Labour"
lab_skill_pie
```


# Investment & Innovation

## Row

```{r}
#| title: "Investments - Past 3 Months"
inv_past_3_bar
```

## Row

```{r}
#| title: "Current Year Investments - Compared to Last Year (Only Q4)"
inv_curr_y_pie
```
```{r}
#| title: "Next Year Investment Expectations - Compared to this Year (Only Q4)"
inv_next_y_pie
```

## Row

```{r}
#| title: "Structure of Investments (Only Q4)"
inv_structure
```

## Row

```{r}
#| title: "Drivers of Investments (Only Q4)"
inv_drivers
```

