project:
  type: website

website:
  navbar:
    right: 
      - href: projects.qmd
        text: Research Projects
        icon: lightbulb
      - href: intelligence.qmd
        text: Industry Intelligence
        icon: graph-up-arrow
      - href: about.qmd
        text: About
    logo: /assets/images/logos/b2flogo.png
    #logo-href: https://www.bridge2food.com
  page-footer: 
    background: "light"
    border: true
    center: |
      <br> Copyright 2024 [Bridge2Food](https://bridge2food.com/). All rights reserved. <br><br>
  bread-crumbs: true
  search: false
  favicon: /assets/images/logos/favicon.ico


format:
  html:
    theme:
      light: cosmo
      dark: solar
    css: styles.css
    toc: true


